[package]
name = "huak"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "A Python package manager written in Rust."
repository = "https://github.com/cnpryer/huak.git"
homepage = "https://github.com/cnpryer/huak.git"
categories = [
    "development-tools"
]

[[bin]]
name = "huak"
path = "./src/bin/huak/main.rs"